name: Semantic Release

on:
  workflow_run:
    workflows: ["Python application"]
    branches: [master]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install semantic-release poetry-plugin-export poetry
          pip check

      - name: Run semantic-release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
