name: Semantic Release

on:
  workflow_run:
    workflows: ["Python application"]
    branches: [master]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install semantic-release poetry-plugin-export

      - name: Run semantic-release
        run: |
          source venv/bin/activate
          semantic-release

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: build/*
          token: ${{ secrets.GH_TOKEN }}
