name: Semantic Release

on:
  workflow_run:
    workflows: ["Python application"]
    branches: [master]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install semantic-release and plugins
        run: |
          python -m pip install semantic-release poetry-plugin-export
          python -m semantic_release --help #verify installation.

      - name: Determine next version and create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -m semantic_release
