name: Semantic Release

on:
  workflow_run:
    workflows: ["Python application"]
    branches: [master]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install poetry-plugin-export poetry

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install semantic-release and plugins
        run: |
          npm install -g semantic-release @semantic-release/changelog

      - name: Verify semantic-release installation
        run: |
          which semantic-release
          semantic-release --version

      - name: Run semantic-release
        run: |
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
